# Generated by Django 5.0.1 on 2024-03-04 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_record_id', models.CharField(blank=True, max_length=200, null=True)),
                ('last_querry_date', models.CharField(blank=True, max_length=200, null=True)),
                ('cui', models.CharField(blank=True, max_length=200, null=True)),
                ('nr_employees', models.CharField(blank=True, max_length=200, null=True)),
                ('denumire', models.CharField(blank=True, max_length=200, null=True)),
                ('adresa', models.CharField(blank=True, max_length=200, null=True)),
                ('nrRegCom', models.CharField(blank=True, max_length=200, null=True)),
                ('telefon', models.CharField(blank=True, max_length=200, null=True)),
                ('fax', models.CharField(blank=True, max_length=200, null=True)),
                ('codPostal', models.CharField(blank=True, max_length=200, null=True)),
                ('act', models.CharField(blank=True, max_length=200, null=True)),
                ('stare_inregistrare', models.CharField(blank=True, max_length=200, null=True)),
                ('data_inregistrare', models.CharField(blank=True, max_length=200, null=True)),
                ('cod_CAEN', models.CharField(blank=True, max_length=200, null=True)),
                ('iban', models.CharField(blank=True, max_length=200, null=True)),
                ('statusRO_e_Factura', models.CharField(blank=True, max_length=200, null=True)),
                ('organFiscalCompetent', models.CharField(blank=True, max_length=200, null=True)),
                ('forma_de_proprietate', models.CharField(blank=True, max_length=200, null=True)),
                ('forma_organizare', models.CharField(blank=True, max_length=200, null=True)),
                ('forma_juridica', models.CharField(blank=True, max_length=200, null=True)),
                ('ceo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervizer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('emp_from_google', models.BooleanField(default=False)),
                ('picture', models.URLField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('registration_method', models.CharField(choices=[('ceo', 'CEO'), ('employee', 'Employee')], default='email', max_length=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
