# Generated by Django 5.0.1 on 2024-02-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='nr_employees',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
