# Generated by Django 5.0.1 on 2024-01-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_querry_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='api_record_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
