# Generated by Django 5.0.1 on 2024-01-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_company_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='user_id',
        ),
    ]
