# Generated by Django 5.0.1 on 2024-01-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_rename_user_company_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user_id',
            new_name='user',
        ),
    ]
