# Generated by Django 5.0.1 on 2024-03-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_homebackground_user_homelayout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebackground',
            name='description',
        ),
        migrations.RemoveField(
            model_name='homebackground',
            name='title',
        ),
    ]
