# Generated by Django 5.0.1 on 2024-03-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0003_remove_homebackground_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebackground',
            name='image',
            field=models.ImageField(default='test.png', upload_to='test/'),
        ),
    ]
