# Generated by Django 5.0.1 on 2024-02-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_googleaccesstokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
